src/beans/Order.java
package beans;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name="Order")
public class Order {

	public String orderNumber;
	public String productName;
	public float price;
	public int quantity;
	
	public Order() {
		super();
	}
	public Order(String orderNumber, String productName, float price, int quantity) {
		super();
		this.orderNumber = orderNumber;
		this.productName = productName;
		this.price = price;
		this.quantity = quantity;
	}

	public String getOrderNumber() {
		return orderNumber;
	}



	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public float getPrice() {
		return price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
}

src/beans/Orders.java
package beans;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@ApplicationScoped
public class Orders {
	
	public List<Order> orders;

	public Orders() {
		super();
		orders = new ArrayList<Order>();
		orders.add(new Order("123", "Key", 5.47f, 10));
	}
	public Order getOrder() {
		return this.orders.get(0);
	}
	
}

src/beans/User.java
package beans;


import java.security.Principal;

import javax.annotation.PostConstruct;
import javax.faces.bean.*;
import javax.faces.context.FacesContext;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@ManagedBean
@SessionScoped
public class User {
	@NotNull()
	@Size(min=5, max=15)
	public String firstName;
	@NotNull()
	@Size(min=5, max=15)
	public String lastName;
	public User(String firstName, String lastName) 
	{
		this.firstName = firstName;
		this.lastName = lastName;
	}
	public User()
	{
		this.firstName = "William";
		this.lastName = "Thornton";
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	@PostConstruct
	public void init() 
	{
		Principal principle= FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal();
		if(principle == null)
		{
			setFirstName("Unknown");
			setLastName("");
		}
		else
		{
			setFirstName(principle.getName());
			setLastName("");
		}

	}
}

src/controllers/FormController.java
package controllers;

import javax.ejb.EJB;
import java.sql.*;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.CustomScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Inject;

import beans.Order;
import beans.User;
import business.AnotherOrdersBusinessService;
import business.MyTimerService;
import business.OrdersBusinessInterface;
import business.OrdersBusinessService;

@ManagedBean
@ViewScoped
public class FormController {
	@Inject
	OrdersBusinessInterface ordInt;
//	@EJB
//	MyTimerService timer;
	public OrdersBusinessInterface getService() {
		return ordInt;
	}
	private void getAllOrders( ) {
		try {
			//establish database connection
			Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "Magrols1!");
			//print success
			System.out.println("Success.");
			
			
			String query = "SELECT * FROM testapp.ORDERS";
			
			Statement stmt = con.createStatement();
			
			ResultSet rs=stmt.executeQuery(query);  
			
			while(rs.next())
			{
				System.out.println(rs.getInt(1)+"  "+rs.getString(3)+"  "+rs.getFloat(4));
			}
			con.close();  
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			System.out.println("Failure.");
		}
				
	}
	private void insertOrder() {
		try {
			Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "Magrols1!");

			System.out.println("Success.");
			
			String query = "INSERT INTO testapp.ORDERS(ORDER_NO, PRODUCT_NAME, PRICE, QUANTITY) VALUES('001122334455', 'This was inserted new', 25.00, 100)";
			
			Statement stmt = con.createStatement();
			
			stmt.executeUpdate(query);  
			
			con.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			System.out.println("Failure.");
		}
				
	}
	
	public String onSendOrder() 
	{
		ordInt.sendOrder(new Order("1234", "Bowflex", 10.0f, 5));
		return "OrderResponse.xhtml";
	}
	public String onLogoff() {
		// Invalidate the Session to clear the security token
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
			
		// Redirect to a protected page (so we get a full HTTP Request) to get Login Page
		return "TestResponse.xhtml?faces-redirect=true";

	}
}

WebContent/OrderResponse.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>JSF Response Page</title>
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>
</h:head> 
<body>
<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="content">
			<p>Hello, #{user.firstName} Your order was processed.</p>
			<h:button value="Test Form" outcome="TestResponse.xhtml"/>
		</ui:define>
</ui:composition>
</body> 
</html>

WebContent/TestResponse.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>Bible Verse Word Count</title>
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>
</h:head> 
<body>
<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="content">
			<p>Hello, #{user.firstName}</p>
			<h:commandButton value="Submit" action="#{formController.onSendOrder()}"/>
			
			<h:dataTable value="#{formController.service.orders}" var="o"
		styleClass="data-table"
		headerClass="data-table-header"
		rowClasses="data-table-odd-row, data-table-even-row">
		
			<h:column>
				<f:facet name="header">Order Number</f:facet>
				#{o.getOrderNumber()}
			</h:column>
			
			<h:column>
				<f:facet name="header">Product Name</f:facet>
				#{o.getProductName()}
			</h:column>
			<h:column>
				<f:facet name="header">Product Price</f:facet>
				#{o.getPrice()}
			</h:column>
			<h:column>
				<f:facet name="header">Quantity</f:facet>
				#{o.getQuantity()}
			</h:column>
			</h:dataTable><br/>
			<h:commandButton value="Logout" action="#{formController.onLogoff()}"/>
		</ui:define>
</ui:composition>
</body> 
</html>

WebContent/faces/LoginError.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>JSF Form Page</title>
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>
</h:head> 
<body>
	<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="content"> 
			<div align="center"> 
				<p>Please enter a user name or password that is authorized to access this
			        application. For this application, this means a user that has been
			        created in the <code>file</code> realm and has been assigned to the
			    <em>group</em> of <code>GcuUser</code>.</p>
			    <p><a href="TestResponse.xhtml">Return to Login</a></p>		
			</div>
	</ui:define>
	</ui:composition>
</body> 
</html>

WebContent/faces/LoginForm.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
	<title>JSF Form Page</title>
	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>
</h:head> 
<body>
	<ui:composition template="/layouts/commonLayout.xhtml">
		<ui:define name="content"> 
			<div align="center"> 
				<form  method="post" action="j_security_check">
					Username: <h:inputText id="j_username" autocomplete="off" /><br/>
					Password: <h:inputSecret id="j_password" autocomplete="off" /><br/>
					<h:commandButton type="submit" value="Submit" />
				</form>
			</div>

	</ui:define>
	</ui:composition>
</body> 
</html>

WebContent/layouts/commonContent.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<body> 

<ui:composition>

<h1>This is default content</h1>

</ui:composition>

</body> 
</html>

WebContent/layouts/commonFooter.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<body> 
	<ui:composition>
		<h5 align="center">@Copyright Grand Canyon University</h5>
	</ui:composition>

</body> 
</html>

WebContent/layouts/commonHeader.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head></h:head> 
<body> 
	<ui:composition>
		<h1 align="center">GCU In-Class Activity</h1>
	</ui:composition>

</body> 
</html>

WebContent/layouts/commonLayout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
<h:outputStylesheet name="common-style.css" library="css"/>
</h:head> 
<body> 
	<div id="page">
		<div id="header" align="center">
			<ui:insert name="header">
			<ui:include src="/layouts/commonHeader.xhtml"/>
			</ui:insert>
		</div>
		
		<div id="content" align="center">
			<ui:insert name="content">
			<ui:include src="/layouts/commonContent.xhtml"/>
			</ui:insert>
		</div>
		
		<div id="footer">
			<ui:insert name="footer">
			<ui:include src="/layouts/commonFooter.xhtml"/>
			</ui:insert>
		</div>
	
	</div>

</body> 
</html>